import {
  Bot,
  BrainCircuit,
  Code2,
  Cpu,
  Database,
  Eye,
  FileText,
  Filter,
  GitBranch,
  Globe,
  Layers,
  Lightbulb,
  MessageSquare,
  Network,
  Search,
  Share2,
  Shield,
  Terminal,
  Wrench,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/** 20 selectable icons for node appearance overrides, keyed by name. */
export const ICON_OPTIONS: Record<string, LucideIcon> = {
  bot: Bot,
  brain: BrainCircuit,
  code: Code2,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  file: FileText,
  filter: Filter,
  branch: GitBranch,
  globe: Globe,
  layers: Layers,
  idea: Lightbulb,
  message: MessageSquare,
  network: Network,
  search: Search,
  share: Share2,
  shield: Shield,
  terminal: Terminal,
  wrench: Wrench,
  zap: Zap,
}
