import {
  Boxes,
  BookOpen,
  Bot,
  Crown,
  Database,
  Flag,
  Gauge,
  GitBranch,
  GitMerge,
  Group,
  HardDrive,
  Layers,
  ListTodo,
  PackageOpen,
  PenLine,
  Play,
  Plug,
  Repeat,
  ShieldCheck,
  Sparkles,
  Split,
  StickyNote,
  Table,
  Terminal,
  UserCheck,
  Users,
  Wrench,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { AgentFlowNodeType, NodeCategory } from '../types'

export interface NodeMeta {
  type: AgentFlowNodeType
  label: string
  category: NodeCategory
  color: string
  icon: LucideIcon
  description: string
}

export const NODE_META: Record<AgentFlowNodeType, NodeMeta> = {
  start: {
    type: 'start',
    label: 'Start',
    category: 'core',
    color: '#16a34a',
    icon: Play,
    description: 'Entry point with input variables',
  },
  llm: {
    type: 'llm',
    label: 'LLM',
    category: 'core',
    color: '#7c3aed',
    icon: Sparkles,
    description: 'Model call with system prompt',
  },
  agent: {
    type: 'agent',
    label: 'Agent',
    category: 'core',
    color: '#4f46e5',
    icon: Bot,
    description: 'LLM + tools reasoning loop',
  },
  tool: {
    type: 'tool',
    label: 'Tool',
    category: 'core',
    color: '#ea580c',
    icon: Wrench,
    description: 'Callable tool with schema',
  },
  memory: {
    type: 'memory',
    label: 'Memory',
    category: 'core',
    color: '#0891b2',
    icon: Database,
    description: 'Short-term, vector or checkpoint',
  },
  output: {
    type: 'output',
    label: 'Output',
    category: 'core',
    color: '#dc2626',
    icon: Flag,
    description: 'Final reply to the user',
  },
  condition: {
    type: 'condition',
    label: 'Condition',
    category: 'flow',
    color: '#ca8a04',
    icon: GitBranch,
    description: 'if / elif / else branching',
  },
  router: {
    type: 'router',
    label: 'Router',
    category: 'flow',
    color: '#65a30d',
    icon: Split,
    description: 'LLM classifier routes to one path',
  },
  guardrail: {
    type: 'guardrail',
    label: 'Guardrail',
    category: 'flow',
    color: '#be123c',
    icon: ShieldCheck,
    description: 'Pass/fail check on the response',
  },
  join: {
    type: 'join',
    label: 'Join',
    category: 'flow',
    color: '#0369a1',
    icon: GitMerge,
    description: 'Wait for branches, then merge',
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    category: 'flow',
    color: '#475569',
    icon: Repeat,
    description: 'Iterate until a condition holds',
  },
  evaluator: {
    type: 'evaluator',
    label: 'Evaluator',
    category: 'flow',
    color: '#a16207',
    icon: Gauge,
    description: 'LLM-as-judge scorer that routes',
  },
  map: {
    type: 'map',
    label: 'Map',
    category: 'flow',
    color: '#0ea5e9',
    icon: Layers,
    description: 'Fan out one branch per item (Send)',
  },
  humanInLoop: {
    type: 'humanInLoop',
    label: 'Human-in-Loop',
    category: 'flow',
    color: '#db2777',
    icon: UserCheck,
    description: 'Pause for human approval',
  },
  supervisor: {
    type: 'supervisor',
    label: 'Supervisor',
    category: 'multiagent',
    color: '#b45309',
    icon: Crown,
    description: 'Routes tasks to worker agents',
  },
  planner: {
    type: 'planner',
    label: 'Planner',
    category: 'multiagent',
    color: '#c026d3',
    icon: ListTodo,
    description: 'Decompose a goal into todos (write_todos)',
  },
  subagent: {
    type: 'subagent',
    label: 'Subagent',
    category: 'multiagent',
    color: '#4338ca',
    icon: PackageOpen,
    description: 'Delegated agent with isolated context',
  },
  swarmWorker: {
    type: 'swarmWorker',
    label: 'Swarm Worker',
    category: 'multiagent',
    color: '#0d9488',
    icon: Users,
    description: 'Peer agent with handoffs',
  },
  retriever: {
    type: 'retriever',
    label: 'Retriever',
    category: 'core',
    color: '#4f46e5',
    icon: BookOpen,
    description: 'Vector store similarity search',
  },
  mcpServer: {
    type: 'mcpServer',
    label: 'MCP Server',
    category: 'core',
    color: '#475569',
    icon: Plug,
    description: 'External tools via MCP',
  },
  longTermStore: {
    type: 'longTermStore',
    label: 'Long-Term Store',
    category: 'core',
    color: '#0e7490',
    icon: HardDrive,
    description: 'Cross-thread namespaced memory (Store)',
  },
  memoryWriter: {
    type: 'memoryWriter',
    label: 'Memory Writer',
    category: 'core',
    color: '#06b6d4',
    icon: PenLine,
    description: 'Extracts memories into the Store',
  },
  subgraph: {
    type: 'subgraph',
    label: 'Subgraph',
    category: 'core',
    color: '#6d28d9',
    icon: Boxes,
    description: 'Compiled inner graph used as a node',
  },
  codeExecutor: {
    type: 'codeExecutor',
    label: 'Code Executor',
    category: 'core',
    color: '#f59e0b',
    icon: Terminal,
    description: 'Run generated code in a sandbox',
  },
  structuredOutput: {
    type: 'structuredOutput',
    label: 'Structured Output',
    category: 'core',
    color: '#7c3aed',
    icon: Table,
    description: 'Enforce a Pydantic schema',
  },
  note: {
    type: 'note',
    label: 'Sticky Note',
    category: 'annotation',
    color: '#57534e',
    icon: StickyNote,
    description: 'Free-text canvas annotation',
  },
  group: {
    type: 'group',
    label: 'Group',
    category: 'annotation',
    color: '#00c4cc',
    icon: Group,
    description: 'Collapsible frame around nodes',
  },
}

/** Narrow an unknown/string node type to its metadata once, safely. */
export function getNodeMeta(type: string | undefined): NodeMeta | undefined {
  return type !== undefined && type in NODE_META
    ? NODE_META[type as AgentFlowNodeType]
    : undefined
}

export const PALETTE: { title: string; types: AgentFlowNodeType[] }[] = [
  {
    title: 'Core',
    types: [
      'start',
      'llm',
      'agent',
      'tool',
      'retriever',
      'mcpServer',
      'structuredOutput',
      'codeExecutor',
      'subgraph',
      'memory',
      'longTermStore',
      'memoryWriter',
      'output',
    ],
  },
  {
    title: 'Flow Control',
    types: ['condition', 'router', 'guardrail', 'evaluator', 'join', 'loop', 'map', 'humanInLoop'],
  },
  {
    title: 'Multi-Agent',
    types: ['supervisor', 'swarmWorker', 'planner', 'subagent'],
  },
  { title: 'Annotation', types: ['note'] },
]
