import { NODE_META } from '../nodes/registry'
import type { AgentFlowEdge, AgentFlowNode, AgentFlowNodeType } from '../types'

/** Annotation-only node types left out of the diagram. */
const EXCLUDED_TYPES: AgentFlowNodeType[] = ['note', 'group']

/** Mermaid identifiers allow only word characters. */
function mermaidId(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_')
}

/** Quoted mermaid labels break on double quotes; pipes break edge text. */
function mermaidLabel(text: string): string {
  return text.replace(/"/g, "'").replace(/\|/g, '/')
}

function nodeShape(type: AgentFlowNodeType, label: string): string {
  const quoted = `"${mermaidLabel(label)}"`
  switch (type) {
    case 'start':
    case 'output':
      return `([${quoted}])`
    case 'condition':
      return `{${quoted}}`
    default:
      return `[${quoted}]`
  }
}

/**
 * Render the canvas as a Mermaid flowchart: stadium Start/Output, diamond
 * conditions, dashed conditional edges, and category colors via classDefs.
 */
export function exportMermaid(nodes: AgentFlowNode[], edges: AgentFlowEdge[]): string {
  const diagramNodes = nodes.filter(
    (n) => n.type !== undefined && !EXCLUDED_TYPES.includes(n.type),
  )
  if (diagramNodes.length === 0) {
    return '%% Add nodes to the canvas to generate a Mermaid diagram.\nflowchart LR\n'
  }
  const ids = new Set(diagramNodes.map((n) => n.id))

  const lines: string[] = [
    '%% Generated by AgentFlow Studio',
    'flowchart LR',
  ]

  for (const node of diagramNodes) {
    if (!node.type) continue
    lines.push(`  ${mermaidId(node.id)}${nodeShape(node.type, node.data.label)}`)
  }

  lines.push('')
  for (const edge of edges) {
    if (!ids.has(edge.source) || !ids.has(edge.target)) continue
    const kind = edge.data?.edgeType ?? 'direct'
    const label =
      typeof edge.label === 'string' && edge.label !== ''
        ? mermaidLabel(edge.label)
        : ''
    const arrow =
      kind === 'conditional'
        ? label !== ''
          ? `-. ${label} .->`
          : '-.->'
        : kind === 'bidirectional'
          ? label !== ''
            ? `<-- ${label} -->`
            : '<-->'
          : label !== ''
            ? `-->|${label}|`
            : '-->'
    lines.push(`  ${mermaidId(edge.source)} ${arrow} ${mermaidId(edge.target)}`)
  }

  // One classDef per node type in use, colored from the palette.
  const typesUsed = [
    ...new Set(
      diagramNodes
        .map((n) => n.type)
        .filter((t): t is AgentFlowNodeType => t !== undefined),
    ),
  ]
  lines.push('')
  for (const type of typesUsed) {
    const color = NODE_META[type].color
    lines.push(
      `  classDef afs_${type} fill:${color},stroke:${color},color:#ffffff`,
    )
  }
  for (const type of typesUsed) {
    const members = diagramNodes
      .filter((n) => n.type === type)
      .map((n) => mermaidId(n.id))
      .join(',')
    lines.push(`  class ${members} afs_${type}`)
  }

  return `${lines.join('\n')}\n`
}
